Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,10 +1,33 @@
-pipeline{
-  agent any;
+
+pipeline {
+  agent any
   stages {
-   stage ('BUILD') {
-     steps{
-       echo "this is"
-       }
+    stage('BUILD') {
+      steps {
+        echo "This is Build stage"
+        sh '''
+          sleep 5
+          exit 0
+        '''
       }
-     }
+    }
+    stage('TEST') {
+      steps {
+        script {
+          // capture exit code
+          def testStatus = sh(script: 'sleep 5; exit 1', returnStatus: true)
+          if (testStatus != 0) {
+            // mark build as failed
+            error("Tests failed, stopping deployment.")
+          }
+        }
+      }
+    }
+    stage('DEPLOY') {
+      steps {
+        echo "This is Deploy stage"
+        sh 'sleep 5'
+      }
+    }
+  }
 }
